// The weekly meal plan, keyed by store. Each store has its own independently
// curated list of 7 recipes, because a single fixed set of exact product
// names can't resolve against every store's different weekly promotions —
// dbPromotionalIngredients only ever holds items currently on a genuine
// deal, never a full catalogue, and different PAK'nSAVE locations run
// different specials. Every ingredient's "match" string was checked against
// that specific store's live data (see supabase-client.js) at the time this
// was written; as real promotions rotate week to week, some may start
// showing "not on special" again and need revisiting.
//
// category: "V" (vegetarian), "NV" (non-vegetarian), "VG" (vegan)
// glutenFree: true if the recipe's packaged ingredients are gluten-free per
// the manufacturer's own product page/ingredient list at the time this was
// written (see PR notes) — an orthogonal tag, independent of category, since
// e.g. a vegan dish can also be GF. Formulations can change: if this matters
// for a real dietary restriction, verify current packaging before relying
// on this tag. The same goes for the vegetarian rennet source behind the
// "V" tag on any cheese ingredient.
// dayOffset: days after the CSV dump date (0 = dump day itself)
// ingredients[].qty: how many pack units of that special the recipe needs
window.MEAL_PLANS_BY_STORE = {
  "PAK'nSAVE Albany": [
    {
      id: 'r1',
      dayOffset: 0,
      name: 'Teriyaki Chicken & Broccoli Stir-Fry Bowl',
      category: 'NV',
      servings: 4,
      emoji: '🍱',
      gradient: ['#ff9a56', '#ff6a88'],
      ingredients: [
        { generic: 'Cooked chicken breast, teriyaki', brand: 'Chop Chop', match: 'Chop Chop Teriyaki Pieces Of Cooked Chicken Breast', qty: 2 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
        { generic: 'Broccoli', brand: '', match: 'Broccoli', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Soy sauce', 'Cooking oil', 'Garlic', 'Sesame oil'],
      instructions: [
        'Cook the rice cups according to the pack instructions (or microwave 90 seconds).',
        'Cut the broccoli into small florets/strips.',
        'Heat a splash of cooking oil in a wok over high heat and stir-fry the broccoli for 3–4 minutes until just tender-crisp.',
        'Add the cooked teriyaki chicken pieces and a splash of soy sauce, tossing until glossy and heated through, about 2 minutes.',
        'Finish with a few drops of sesame oil, season with salt and pepper, and serve over the warm rice.',
      ],
    },
    {
      id: 'r2',
      dayOffset: 1,
      name: 'Chickpea & Cauliflower Korma Bowl',
      category: 'V',
      glutenFree: true,
      servings: 4,
      emoji: '🍛',
      gradient: ['#f7971e', '#ffd200'],
      ingredients: [
        { generic: 'Korma curry simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Korma Simmer Sauce', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic', 'Onion'],
      instructions: [
        'Cut the cauliflower into bite-sized pieces. Rinse and drain the chickpeas.',
        'Cook the rice cups according to the pack instructions.',
        'Heat oil in a large pot, soften a diced onion and a crushed garlic clove for 2–3 minutes.',
        'Add the cauliflower, chickpeas and korma sauce, plus a splash of water. Cover and simmer 12–15 minutes until tender.',
        'Season to taste and serve over the warm rice.',
      ],
    },
    {
      id: 'r3',
      dayOffset: 2,
      name: 'Garlic Tomato Spaghetti with Green Capsicum',
      category: 'V',
      servings: 4,
      emoji: '🍝',
      gradient: ['#56ab2f', '#a8e063'],
      ingredients: [
        { generic: 'Dry spaghetti', brand: 'Diamond', match: 'Diamond Spaghetti Pasta', qty: 1 },
        { generic: 'Roasted garlic tomato & onion pasta sauce', brand: "Leggo's", match: "Leggo's Roasted Garlic Chunky Tomato & Onion Pasta Sauce", qty: 1 },
        { generic: 'Capsicum, green', brand: '', match: 'Green Capsicum', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic', 'Dried basil'],
      instructions: [
        'Cook the spaghetti in a large pot of salted boiling water according to the pack instructions, then drain.',
        'Thinly slice the green capsicum.',
        'Heat a little olive oil in a large pan and soften the green capsicum for 3–4 minutes with a crushed garlic clove.',
        'Stir in the tomato & onion pasta sauce and simmer for 3–4 minutes.',
        'Toss the drained spaghetti through the sauce, season with salt, pepper and a pinch of dried basil, and serve.',
      ],
    },
    {
      id: 'r4',
      dayOffset: 3,
      name: 'Tuna & Red Capsicum Pasta Bake',
      category: 'NV',
      servings: 4,
      emoji: '🐟',
      gradient: ['#2193b0', '#6dd5ed'],
      ingredients: [
        { generic: 'Dry penne pasta', brand: 'Diamond', match: 'Diamond Penne Pasta', qty: 1 },
        { generic: 'Tuna chunks in spring water', brand: 'Sealord', match: 'Sealord Chunky Style Tuna In Spring Water', qty: 2 },
        { generic: 'Creamy tomato & mozzarella pasta bake sauce', brand: "Leggo's", match: "Leggo's Creamy Tomato Mozzarella Pasta Bake", qty: 1 },
        { generic: 'Capsicum, red', brand: '', match: 'Red Capsicum', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic'],
      instructions: [
        'Preheat the oven to 200°C. Cook the penne in a large pot of salted boiling water until just al dente, then drain.',
        'Dice the red capsicum and flake the drained tuna.',
        'Mix the cooked penne, red capsicum, tuna and creamy tomato bake sauce together in a baking dish, seasoning with salt, pepper and a crushed garlic clove.',
        'Bake for 15–18 minutes until bubbling, then rest 5 minutes before serving.',
      ],
    },
    {
      id: 'r5',
      dayOffset: 4,
      name: 'Vegan Black Bean & Kidney Bean Chilli',
      category: 'VG',
      servings: 4,
      emoji: '🌶️',
      gradient: ['#c31432', '#240b36'],
      ingredients: [
        { generic: 'Baked beans in tomato sauce, canned', brand: 'Oak', match: 'Oak Baked Beans In Tomato Sauce', qty: 1 },
        { generic: 'Black beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Black Beans', qty: 1 },
        { generic: 'Red kidney beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Red Kidney Beans', qty: 1 },
        { generic: 'Long grain rice, dry', brand: 'Fortune', match: 'Fortune Long Grain Rice', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Cumin', 'Chilli powder', 'Cooking oil', 'Onion'],
      instructions: [
        'Cook the rice according to the pack instructions.',
        'Dice the onion. Rinse and drain the black beans and kidney beans.',
        'Heat oil in a pot and soften the onion for 3–4 minutes with a pinch of cumin and chilli powder.',
        'Stir in the baked beans, black beans and kidney beans, then simmer uncovered for 12–15 minutes, stirring occasionally, until thickened.',
        'Season to taste and serve spooned over the rice.',
      ],
    },
    {
      id: 'r6',
      dayOffset: 5,
      name: 'Butter Chicken Thigh Cutlets with Rice',
      category: 'NV',
      glutenFree: true,
      servings: 4,
      emoji: '🍗',
      gradient: ['#ee0979', '#ff6a00'],
      ingredients: [
        { generic: 'Chicken thigh cutlets, bone-in', brand: '', match: 'NZ Chicken Thigh Bone in Cutlets', qty: 1 },
        { generic: 'Butter chicken simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Butter Chicken Simmer Sauce', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic'],
      instructions: [
        'Season the chicken thigh cutlets with salt and pepper.',
        'Heat oil in a large pan over medium-high heat and brown the cutlets for 3–4 minutes each side.',
        'Add the butter chicken sauce and a crushed garlic clove, cover and simmer for 20–25 minutes until the chicken is cooked through, turning once.',
        'Cook the rice cups according to the pack instructions.',
        'Serve the chicken and sauce spooned over the warm rice.',
      ],
    },
    {
      id: 'r7',
      dayOffset: 6,
      name: 'Roast Cauliflower & Chickpea Salad',
      category: 'VG',
      glutenFree: true,
      servings: 4,
      emoji: '🥗',
      gradient: ['#11998e', '#38ef7d'],
      ingredients: [
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Carrots', brand: '', match: 'Carrots', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Balsamic vinegar', 'Garlic'],
      instructions: [
        'Preheat the oven to 210°C. Cut the cauliflower into florets and the carrots into batons.',
        'Toss the cauliflower and carrots in olive oil, salt and pepper.',
        'Roast for 25–30 minutes, turning once, until caramelised and tender.',
        'Rinse and drain the chickpeas, then toss through the warm roasted vegetables.',
        'Finish with a drizzle of olive oil and balsamic vinegar.',
      ],
    },
  ],

  "PAK'nSAVE Westgate": [
    {
      id: 'r1',
      dayOffset: 0,
      name: 'Teriyaki Chicken & Green Cabbage Stir-Fry Bowl',
      category: 'NV',
      servings: 4,
      emoji: '🍱',
      gradient: ['#ff9a56', '#ff6a88'],
      ingredients: [
        { generic: 'Cooked chicken breast, teriyaki', brand: 'Chop Chop', match: 'Chop Chop Teriyaki Pieces Of Cooked Chicken Breast', qty: 2 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
        { generic: 'Green cabbage', brand: '', match: 'Green Cabbage', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Soy sauce', 'Cooking oil', 'Garlic', 'Sesame oil'],
      instructions: [
        'Cook the rice cups according to the pack instructions (or microwave 90 seconds).',
        'Cut the green cabbage into small florets/strips.',
        'Heat a splash of cooking oil in a wok over high heat and stir-fry the green cabbage for 3–4 minutes until just tender-crisp.',
        'Add the cooked teriyaki chicken pieces and a splash of soy sauce, tossing until glossy and heated through, about 2 minutes.',
        'Finish with a few drops of sesame oil, season with salt and pepper, and serve over the warm rice.',
      ],
    },
    {
      id: 'r2',
      dayOffset: 1,
      name: 'Chickpea & Cauliflower Korma Bowl',
      category: 'V',
      glutenFree: true,
      servings: 4,
      emoji: '🍛',
      gradient: ['#f7971e', '#ffd200'],
      ingredients: [
        { generic: 'Korma curry simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Korma Simmer Sauce', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic', 'Onion'],
      instructions: [
        'Cut the cauliflower into bite-sized pieces. Rinse and drain the chickpeas.',
        'Cook the rice cups according to the pack instructions.',
        'Heat oil in a large pot, soften a diced onion and a crushed garlic clove for 2–3 minutes.',
        'Add the cauliflower, chickpeas and korma sauce, plus a splash of water. Cover and simmer 12–15 minutes until tender.',
        'Season to taste and serve over the warm rice.',
      ],
    },
    {
      id: 'r3',
      dayOffset: 2,
      name: 'Garlic Tomato Spaghetti with Green Cabbage',
      category: 'V',
      servings: 4,
      emoji: '🍝',
      gradient: ['#56ab2f', '#a8e063'],
      ingredients: [
        { generic: 'Dry spaghetti', brand: 'Diamond', match: 'Diamond Spaghetti Pasta', qty: 1 },
        { generic: 'Roasted garlic tomato & onion pasta sauce', brand: "Leggo's", match: "Leggo's Roasted Garlic Chunky Tomato & Onion Pasta Sauce", qty: 1 },
        { generic: 'Green cabbage', brand: '', match: 'Green Cabbage', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic', 'Dried basil'],
      instructions: [
        'Cook the spaghetti in a large pot of salted boiling water according to the pack instructions, then drain.',
        'Thinly slice the green cabbage.',
        'Heat a little olive oil in a large pan and soften the green cabbage for 3–4 minutes with a crushed garlic clove.',
        'Stir in the tomato & onion pasta sauce and simmer for 3–4 minutes.',
        'Toss the drained spaghetti through the sauce, season with salt, pepper and a pinch of dried basil, and serve.',
      ],
    },
    {
      id: 'r4',
      dayOffset: 3,
      name: 'Tuna & Carrots Pasta Bake',
      category: 'NV',
      servings: 4,
      emoji: '🐟',
      gradient: ['#2193b0', '#6dd5ed'],
      ingredients: [
        { generic: 'Dry penne pasta', brand: 'Diamond', match: 'Diamond Penne Pasta', qty: 1 },
        { generic: 'Tuna chunks in spring water', brand: 'Sealord', match: 'Sealord Chunky Style Tuna In Spring Water', qty: 2 },
        { generic: 'Creamy tomato & mozzarella pasta bake sauce', brand: "Leggo's", match: "Leggo's Creamy Tomato Mozzarella Pasta Bake", qty: 1 },
        { generic: 'Carrots', brand: '', match: 'Carrots', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic'],
      instructions: [
        'Preheat the oven to 200°C. Cook the penne in a large pot of salted boiling water until just al dente, then drain.',
        'Dice the carrots and flake the drained tuna.',
        'Mix the cooked penne, carrots, tuna and creamy tomato bake sauce together in a baking dish, seasoning with salt, pepper and a crushed garlic clove.',
        'Bake for 15–18 minutes until bubbling, then rest 5 minutes before serving.',
      ],
    },
    {
      id: 'r5',
      dayOffset: 4,
      name: 'Vegan Black Bean & Kidney Bean Chilli',
      category: 'VG',
      servings: 4,
      emoji: '🌶️',
      gradient: ['#c31432', '#240b36'],
      ingredients: [
        { generic: 'Baked beans in tomato sauce, canned', brand: 'Oak', match: 'Oak Baked Beans In Tomato Sauce', qty: 1 },
        { generic: 'Black beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Black Beans', qty: 1 },
        { generic: 'Red kidney beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Red Kidney Beans', qty: 1 },
        { generic: 'Long grain rice, dry', brand: 'Fortune', match: 'Fortune Long Grain Rice', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Cumin', 'Chilli powder', 'Cooking oil', 'Onion'],
      instructions: [
        'Cook the rice according to the pack instructions.',
        'Dice the onion. Rinse and drain the black beans and kidney beans.',
        'Heat oil in a pot and soften the onion for 3–4 minutes with a pinch of cumin and chilli powder.',
        'Stir in the baked beans, black beans and kidney beans, then simmer uncovered for 12–15 minutes, stirring occasionally, until thickened.',
        'Season to taste and serve spooned over the rice.',
      ],
    },
    {
      id: 'r6',
      dayOffset: 5,
      name: 'Butter Chicken Thigh Cutlets with Rice',
      category: 'NV',
      glutenFree: true,
      servings: 4,
      emoji: '🍗',
      gradient: ['#ee0979', '#ff6a00'],
      ingredients: [
        { generic: 'Chicken thigh cutlets, bone-in', brand: '', match: 'NZ Chicken Thigh Bone in Cutlets', qty: 1 },
        { generic: 'Butter chicken simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Butter Chicken Simmer Sauce', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic'],
      instructions: [
        'Season the chicken thigh cutlets with salt and pepper.',
        'Heat oil in a large pan over medium-high heat and brown the cutlets for 3–4 minutes each side.',
        'Add the butter chicken sauce and a crushed garlic clove, cover and simmer for 20–25 minutes until the chicken is cooked through, turning once.',
        'Cook the rice cups according to the pack instructions.',
        'Serve the chicken and sauce spooned over the warm rice.',
      ],
    },
    {
      id: 'r7',
      dayOffset: 6,
      name: 'Roast Cauliflower & Chickpea Salad',
      category: 'VG',
      glutenFree: true,
      servings: 4,
      emoji: '🥗',
      gradient: ['#11998e', '#38ef7d'],
      ingredients: [
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Carrots', brand: '', match: 'Carrots', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Balsamic vinegar', 'Garlic'],
      instructions: [
        'Preheat the oven to 210°C. Cut the cauliflower into florets and the carrots into batons.',
        'Toss the cauliflower and carrots in olive oil, salt and pepper.',
        'Roast for 25–30 minutes, turning once, until caramelised and tender.',
        'Rinse and drain the chickpeas, then toss through the warm roasted vegetables.',
        'Finish with a drizzle of olive oil and balsamic vinegar.',
      ],
    },
  ],

  "PAK'nSAVE Lincoln Road": [
    {
      id: 'r1',
      dayOffset: 0,
      name: 'Teriyaki Chicken & Avocado Rice Bowl',
      category: 'NV',
      servings: 4,
      emoji: '🍱',
      gradient: ['#ff9a56', '#ff6a88'],
      // No fresh vegetables of any kind were on special at this store when
      // this was written — avocado (the only fresh produce that was live)
      // stands in for a cooked vegetable.
      ingredients: [
        { generic: 'Cooked chicken breast, teriyaki', brand: 'Chop Chop', match: 'Chop Chop Teriyaki Pieces Of Cooked Chicken Breast', qty: 2 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
        { generic: 'Avocado', brand: '', match: 'Avocado', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Soy sauce', 'Cooking oil', 'Sesame oil'],
      instructions: [
        'Cook the rice cups according to the pack instructions (or microwave 90 seconds).',
        'Warm the teriyaki chicken pieces through in a splash of cooking oil and soy sauce, 2–3 minutes.',
        'Halve, stone and slice the avocado.',
        'Spoon the warm chicken over the rice and top with the sliced avocado.',
        'Finish with a few drops of sesame oil and serve immediately.',
      ],
    },
    {
      id: 'r2',
      dayOffset: 1,
      name: 'Chickpea Korma Bowl',
      category: 'V',
      glutenFree: true,
      servings: 4,
      emoji: '🍛',
      gradient: ['#f7971e', '#ffd200'],
      // No fresh vegetables were on special at this store when this was
      // written, so this is a simpler chickpea-and-rice curry without one.
      ingredients: [
        { generic: 'Korma curry simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Korma Simmer Sauce', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic', 'Onion'],
      instructions: [
        'Rinse and drain the chickpeas.',
        'Cook the rice cups according to the pack instructions.',
        'Heat oil in a pot, soften a diced onion and a crushed garlic clove for 2–3 minutes.',
        'Add the chickpeas and korma sauce, plus a splash of water. Cover and simmer 10 minutes.',
        'Season to taste and serve over the warm rice.',
      ],
    },
    {
      id: 'r3',
      dayOffset: 2,
      name: 'Garlic Tomato Spaghetti',
      category: 'V',
      servings: 4,
      emoji: '🍝',
      gradient: ['#56ab2f', '#a8e063'],
      ingredients: [
        { generic: 'Dry spaghetti', brand: 'Diamond', match: 'Diamond Spaghetti Pasta', qty: 1 },
        { generic: 'Roasted garlic tomato & onion pasta sauce', brand: "Leggo's", match: "Leggo's Roasted Garlic Chunky Tomato & Onion Pasta Sauce", qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic', 'Dried basil'],
      instructions: [
        'Cook the spaghetti in a large pot of salted boiling water according to the pack instructions, then drain.',
        'Warm the tomato & onion pasta sauce in a pan with a crushed garlic clove for 3–4 minutes.',
        'Toss the drained spaghetti through the sauce.',
        'Season with salt, pepper and a pinch of dried basil, and serve.',
      ],
    },
    {
      id: 'r4',
      dayOffset: 3,
      name: 'Garlic Prawn Spaghetti',
      category: 'NV',
      servings: 4,
      emoji: '🍤',
      gradient: ['#2193b0', '#6dd5ed'],
      // No dry pasta shape was paired with fresh vegetables this week either
      // — frozen garlic prawns (confirmed live) carry this dish instead.
      ingredients: [
        { generic: 'Dry spaghetti', brand: 'Diamond', match: 'Diamond Spaghetti Pasta', qty: 1 },
        { generic: 'Garlic prawns, frozen', brand: '', match: 'Garlic Prawns (Frozen)', qty: 2 },
        { generic: 'Roasted garlic tomato & onion pasta sauce', brand: "Leggo's", match: "Leggo's Roasted Garlic Chunky Tomato & Onion Pasta Sauce", qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic', 'Chilli flakes'],
      instructions: [
        'Cook the spaghetti in a large pot of salted boiling water according to the pack instructions, then drain.',
        'Cook the garlic prawns from frozen in a splash of olive oil according to the pack instructions, until pink and cooked through.',
        'Add the tomato & onion pasta sauce to the pan and simmer for 2–3 minutes.',
        'Toss the drained spaghetti through the prawns and sauce, season with salt, pepper and a pinch of chilli flakes, and serve.',
      ],
    },
    {
      id: 'r5',
      dayOffset: 4,
      name: 'Vegan Black Bean & Kidney Bean Chilli',
      category: 'VG',
      servings: 4,
      emoji: '🌶️',
      gradient: ['#c31432', '#240b36'],
      ingredients: [
        { generic: 'Baked beans in tomato sauce, canned', brand: 'Oak', match: 'Oak Baked Beans In Tomato Sauce', qty: 1 },
        { generic: 'Black beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Black Beans', qty: 1 },
        { generic: 'Red kidney beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Red Kidney Beans', qty: 1 },
        { generic: 'Long grain rice, dry', brand: 'Fortune', match: 'Fortune Long Grain Rice', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Cumin', 'Chilli powder', 'Cooking oil', 'Onion'],
      instructions: [
        'Cook the rice according to the pack instructions.',
        'Dice the onion. Rinse and drain the black beans and kidney beans.',
        'Heat oil in a pot and soften the onion for 3–4 minutes with a pinch of cumin and chilli powder.',
        'Stir in the baked beans, black beans and kidney beans, then simmer uncovered for 12–15 minutes, stirring occasionally, until thickened.',
        'Season to taste and serve spooned over the rice.',
      ],
    },
    {
      id: 'r6',
      dayOffset: 5,
      name: 'Butter Chicken Thigh Cutlets with Rice',
      category: 'NV',
      glutenFree: true,
      servings: 4,
      emoji: '🍗',
      gradient: ['#ee0979', '#ff6a00'],
      ingredients: [
        { generic: 'Chicken thigh cutlets, bone-in', brand: '', match: 'NZ Chicken Thigh Bone in Cutlets', qty: 1 },
        { generic: 'Butter chicken simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Butter Chicken Simmer Sauce', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic'],
      instructions: [
        'Season the chicken thigh cutlets with salt and pepper.',
        'Heat oil in a large pan over medium-high heat and brown the cutlets for 3–4 minutes each side.',
        'Add the butter chicken sauce and a crushed garlic clove, cover and simmer for 20–25 minutes until the chicken is cooked through, turning once.',
        'Cook the rice cups according to the pack instructions.',
        'Serve the chicken and sauce spooned over the warm rice.',
      ],
    },
    {
      id: 'r7',
      dayOffset: 6,
      name: 'Sweet Chilli Prawn Skewers with Rice & Avocado',
      category: 'NV',
      servings: 4,
      emoji: '🥢',
      gradient: ['#11998e', '#38ef7d'],
      // No fresh vegetables were on special at this store to roast for a
      // salad, so this leans on the other fresh item that was: avocado.
      ingredients: [
        { generic: 'Sweet chilli prawn skewer, frozen', brand: '', match: 'Sweet Chilli Prawn Skewer (Prefrozen)', qty: 4 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
        { generic: 'Avocado', brand: '', match: 'Avocado', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Lime (optional)'],
      instructions: [
        'Cook the prawn skewers from frozen according to the pack instructions (grill, pan-fry or oven-bake).',
        'Cook the rice cups according to the pack instructions.',
        'Halve, stone and slice the avocado.',
        'Serve the skewers over the rice with the sliced avocado alongside, seasoned with salt and pepper.',
      ],
    },
  ],

  "PAK'nSAVE Sylvia Park": [
    {
      id: 'r1',
      dayOffset: 0,
      name: 'Teriyaki Chicken & Wong Bok Cabbage Stir-Fry Bowl',
      category: 'NV',
      servings: 4,
      emoji: '🍱',
      gradient: ['#ff9a56', '#ff6a88'],
      ingredients: [
        { generic: 'Cooked chicken breast, teriyaki', brand: 'Chop Chop', match: 'Chop Chop Teriyaki Pieces Of Cooked Chicken Breast', qty: 2 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
        { generic: 'Wong bok cabbage', brand: '', match: 'Chinese Cabbage (Wong Bok)', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Soy sauce', 'Cooking oil', 'Garlic', 'Sesame oil'],
      instructions: [
        'Cook the rice cups according to the pack instructions (or microwave 90 seconds).',
        'Cut the wong bok cabbage into small florets/strips.',
        'Heat a splash of cooking oil in a wok over high heat and stir-fry the wong bok cabbage for 3–4 minutes until just tender-crisp.',
        'Add the cooked teriyaki chicken pieces and a splash of soy sauce, tossing until glossy and heated through, about 2 minutes.',
        'Finish with a few drops of sesame oil, season with salt and pepper, and serve over the warm rice.',
      ],
    },
    {
      id: 'r2',
      dayOffset: 1,
      name: 'Chickpea & Pumpkin Korma Bowl',
      category: 'V',
      glutenFree: true,
      servings: 4,
      emoji: '🍛',
      gradient: ['#f7971e', '#ffd200'],
      ingredients: [
        { generic: 'Korma curry simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Korma Simmer Sauce', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
        { generic: 'Pumpkin', brand: '', match: 'Crown Pumpkin', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic', 'Onion'],
      instructions: [
        'Cut the pumpkin into bite-sized pieces. Rinse and drain the chickpeas.',
        'Cook the rice cups according to the pack instructions.',
        'Heat oil in a large pot, soften a diced onion and a crushed garlic clove for 2–3 minutes.',
        'Add the pumpkin, chickpeas and korma sauce, plus a splash of water. Cover and simmer 12–15 minutes until tender.',
        'Season to taste and serve over the warm rice.',
      ],
    },
    {
      id: 'r3',
      dayOffset: 2,
      name: 'Garlic Tomato Spaghetti with Green Capsicum',
      category: 'V',
      servings: 4,
      emoji: '🍝',
      gradient: ['#56ab2f', '#a8e063'],
      ingredients: [
        { generic: 'Dry spaghetti', brand: 'Diamond', match: 'Diamond Spaghetti Pasta', qty: 1 },
        { generic: 'Roasted garlic tomato & onion pasta sauce', brand: "Leggo's", match: "Leggo's Roasted Garlic Chunky Tomato & Onion Pasta Sauce", qty: 1 },
        { generic: 'Capsicum, green', brand: '', match: 'Green Capsicum', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic', 'Dried basil'],
      instructions: [
        'Cook the spaghetti in a large pot of salted boiling water according to the pack instructions, then drain.',
        'Thinly slice the green capsicum.',
        'Heat a little olive oil in a large pan and soften the green capsicum for 3–4 minutes with a crushed garlic clove.',
        'Stir in the tomato & onion pasta sauce and simmer for 3–4 minutes.',
        'Toss the drained spaghetti through the sauce, season with salt, pepper and a pinch of dried basil, and serve.',
      ],
    },
    {
      id: 'r4',
      dayOffset: 3,
      name: 'Tuna & Yellow Capsicum Pasta Bake',
      category: 'NV',
      servings: 4,
      emoji: '🐟',
      gradient: ['#2193b0', '#6dd5ed'],
      ingredients: [
        { generic: 'Dry penne pasta', brand: 'Diamond', match: 'Diamond Penne Pasta', qty: 1 },
        { generic: 'Tuna chunks in spring water', brand: 'Sealord', match: 'Sealord Chunky Style Tuna In Spring Water', qty: 2 },
        { generic: 'Creamy tomato & mozzarella pasta bake sauce', brand: "Leggo's", match: "Leggo's Creamy Tomato Mozzarella Pasta Bake", qty: 1 },
        { generic: 'Capsicum, yellow', brand: '', match: 'Yellow Capsicum', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic'],
      instructions: [
        'Preheat the oven to 200°C. Cook the penne in a large pot of salted boiling water until just al dente, then drain.',
        'Dice the yellow capsicum and flake the drained tuna.',
        'Mix the cooked penne, yellow capsicum, tuna and creamy tomato bake sauce together in a baking dish, seasoning with salt, pepper and a crushed garlic clove.',
        'Bake for 15–18 minutes until bubbling, then rest 5 minutes before serving.',
      ],
    },
    {
      id: 'r5',
      dayOffset: 4,
      name: 'Vegan Black Bean & Kidney Bean Chilli',
      category: 'VG',
      servings: 4,
      emoji: '🌶️',
      gradient: ['#c31432', '#240b36'],
      ingredients: [
        { generic: 'Baked beans in tomato sauce, canned', brand: 'Oak', match: 'Oak Baked Beans In Tomato Sauce', qty: 1 },
        { generic: 'Black beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Black Beans', qty: 1 },
        { generic: 'Red kidney beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Red Kidney Beans', qty: 1 },
        { generic: 'Long grain rice, dry', brand: 'Fortune', match: 'Fortune Long Grain Rice', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Cumin', 'Chilli powder', 'Cooking oil', 'Onion'],
      instructions: [
        'Cook the rice according to the pack instructions.',
        'Dice the onion. Rinse and drain the black beans and kidney beans.',
        'Heat oil in a pot and soften the onion for 3–4 minutes with a pinch of cumin and chilli powder.',
        'Stir in the baked beans, black beans and kidney beans, then simmer uncovered for 12–15 minutes, stirring occasionally, until thickened.',
        'Season to taste and serve spooned over the rice.',
      ],
    },
    {
      id: 'r6',
      dayOffset: 5,
      name: 'Butter Chicken Thigh Cutlets with Rice',
      category: 'NV',
      glutenFree: true,
      servings: 4,
      emoji: '🍗',
      gradient: ['#ee0979', '#ff6a00'],
      ingredients: [
        { generic: 'Chicken thigh cutlets, bone-in', brand: '', match: 'NZ Chicken Thigh Bone in Cutlets', qty: 1 },
        { generic: 'Butter chicken simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Butter Chicken Simmer Sauce', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic'],
      instructions: [
        'Season the chicken thigh cutlets with salt and pepper.',
        'Heat oil in a large pan over medium-high heat and brown the cutlets for 3–4 minutes each side.',
        'Add the butter chicken sauce and a crushed garlic clove, cover and simmer for 20–25 minutes until the chicken is cooked through, turning once.',
        'Cook the rice cups according to the pack instructions.',
        'Serve the chicken and sauce spooned over the warm rice.',
      ],
    },
    {
      id: 'r7',
      dayOffset: 6,
      name: 'Roast Cauliflower & Chickpea Salad',
      category: 'VG',
      glutenFree: true,
      servings: 4,
      emoji: '🥗',
      gradient: ['#11998e', '#38ef7d'],
      ingredients: [
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Carrots', brand: '', match: 'Carrots', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Balsamic vinegar', 'Garlic'],
      instructions: [
        'Preheat the oven to 210°C. Cut the cauliflower into florets and the carrots into batons.',
        'Toss the cauliflower and carrots in olive oil, salt and pepper.',
        'Roast for 25–30 minutes, turning once, until caramelised and tender.',
        'Rinse and drain the chickpeas, then toss through the warm roasted vegetables.',
        'Finish with a drizzle of olive oil and balsamic vinegar.',
      ],
    },
  ],

  "PAK'nSAVE Royal Oak": [
    {
      id: 'r1',
      dayOffset: 0,
      name: 'Teriyaki Chicken & Wong Bok Cabbage Stir-Fry Bowl',
      category: 'NV',
      servings: 4,
      emoji: '🍱',
      gradient: ['#ff9a56', '#ff6a88'],
      ingredients: [
        { generic: 'Cooked chicken breast, teriyaki', brand: 'Chop Chop', match: 'Chop Chop Teriyaki Pieces Of Cooked Chicken Breast', qty: 2 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
        { generic: 'Wong bok cabbage', brand: '', match: 'Chinese Cabbage (Wong Bok)', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Soy sauce', 'Cooking oil', 'Garlic', 'Sesame oil'],
      instructions: [
        'Cook the rice cups according to the pack instructions (or microwave 90 seconds).',
        'Cut the wong bok cabbage into small florets/strips.',
        'Heat a splash of cooking oil in a wok over high heat and stir-fry the wong bok cabbage for 3–4 minutes until just tender-crisp.',
        'Add the cooked teriyaki chicken pieces and a splash of soy sauce, tossing until glossy and heated through, about 2 minutes.',
        'Finish with a few drops of sesame oil, season with salt and pepper, and serve over the warm rice.',
      ],
    },
    {
      id: 'r2',
      dayOffset: 1,
      name: 'Chickpea & Cauliflower Korma Bowl',
      category: 'V',
      glutenFree: true,
      servings: 4,
      emoji: '🍛',
      gradient: ['#f7971e', '#ffd200'],
      ingredients: [
        { generic: 'Korma curry simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Korma Simmer Sauce', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic', 'Onion'],
      instructions: [
        'Cut the cauliflower into bite-sized pieces. Rinse and drain the chickpeas.',
        'Cook the rice cups according to the pack instructions.',
        'Heat oil in a large pot, soften a diced onion and a crushed garlic clove for 2–3 minutes.',
        'Add the cauliflower, chickpeas and korma sauce, plus a splash of water. Cover and simmer 12–15 minutes until tender.',
        'Season to taste and serve over the warm rice.',
      ],
    },
    {
      id: 'r3',
      dayOffset: 2,
      name: 'Garlic Tomato Spaghetti with Green Cabbage',
      category: 'V',
      servings: 4,
      emoji: '🍝',
      gradient: ['#56ab2f', '#a8e063'],
      ingredients: [
        { generic: 'Dry spaghetti', brand: 'Diamond', match: 'Diamond Spaghetti Pasta', qty: 1 },
        { generic: 'Roasted garlic tomato & onion pasta sauce', brand: "Leggo's", match: "Leggo's Roasted Garlic Chunky Tomato & Onion Pasta Sauce", qty: 1 },
        { generic: 'Green cabbage', brand: '', match: 'Green Cabbage', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic', 'Dried basil'],
      instructions: [
        'Cook the spaghetti in a large pot of salted boiling water according to the pack instructions, then drain.',
        'Thinly slice the green cabbage.',
        'Heat a little olive oil in a large pan and soften the green cabbage for 3–4 minutes with a crushed garlic clove.',
        'Stir in the tomato & onion pasta sauce and simmer for 3–4 minutes.',
        'Toss the drained spaghetti through the sauce, season with salt, pepper and a pinch of dried basil, and serve.',
      ],
    },
    {
      id: 'r4',
      dayOffset: 3,
      name: 'Tuna & Carrots Pasta Bake',
      category: 'NV',
      servings: 4,
      emoji: '🐟',
      gradient: ['#2193b0', '#6dd5ed'],
      ingredients: [
        { generic: 'Dry penne pasta', brand: 'Diamond', match: 'Diamond Penne Pasta', qty: 1 },
        { generic: 'Tuna chunks in spring water', brand: 'Sealord', match: 'Sealord Chunky Style Tuna In Spring Water', qty: 2 },
        { generic: 'Creamy tomato & mozzarella pasta bake sauce', brand: "Leggo's", match: "Leggo's Creamy Tomato Mozzarella Pasta Bake", qty: 1 },
        { generic: 'Carrots', brand: '', match: 'Carrots', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic'],
      instructions: [
        'Preheat the oven to 200°C. Cook the penne in a large pot of salted boiling water until just al dente, then drain.',
        'Dice the carrots and flake the drained tuna.',
        'Mix the cooked penne, carrots, tuna and creamy tomato bake sauce together in a baking dish, seasoning with salt, pepper and a crushed garlic clove.',
        'Bake for 15–18 minutes until bubbling, then rest 5 minutes before serving.',
      ],
    },
    {
      id: 'r5',
      dayOffset: 4,
      name: 'Vegan Black Bean & Kidney Bean Chilli',
      category: 'VG',
      servings: 4,
      emoji: '🌶️',
      gradient: ['#c31432', '#240b36'],
      ingredients: [
        { generic: 'Baked beans in tomato sauce, canned', brand: 'Oak', match: 'Oak Baked Beans In Tomato Sauce', qty: 1 },
        { generic: 'Black beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Black Beans', qty: 1 },
        { generic: 'Red kidney beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Red Kidney Beans', qty: 1 },
        { generic: 'Long grain rice, dry', brand: 'Fortune', match: 'Fortune Long Grain Rice', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Cumin', 'Chilli powder', 'Cooking oil', 'Onion'],
      instructions: [
        'Cook the rice according to the pack instructions.',
        'Dice the onion. Rinse and drain the black beans and kidney beans.',
        'Heat oil in a pot and soften the onion for 3–4 minutes with a pinch of cumin and chilli powder.',
        'Stir in the baked beans, black beans and kidney beans, then simmer uncovered for 12–15 minutes, stirring occasionally, until thickened.',
        'Season to taste and serve spooned over the rice.',
      ],
    },
    {
      id: 'r6',
      dayOffset: 5,
      name: 'Butter Chicken Thigh Cutlets with Rice',
      category: 'NV',
      glutenFree: true,
      servings: 4,
      emoji: '🍗',
      gradient: ['#ee0979', '#ff6a00'],
      ingredients: [
        { generic: 'Chicken thigh cutlets, bone-in', brand: '', match: 'NZ Chicken Thigh Bone in Cutlets', qty: 1 },
        { generic: 'Butter chicken simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Butter Chicken Simmer Sauce', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic'],
      instructions: [
        'Season the chicken thigh cutlets with salt and pepper.',
        'Heat oil in a large pan over medium-high heat and brown the cutlets for 3–4 minutes each side.',
        'Add the butter chicken sauce and a crushed garlic clove, cover and simmer for 20–25 minutes until the chicken is cooked through, turning once.',
        'Cook the rice cups according to the pack instructions.',
        'Serve the chicken and sauce spooned over the warm rice.',
      ],
    },
    {
      id: 'r7',
      dayOffset: 6,
      name: 'Roast Cauliflower & Chickpea Salad',
      category: 'VG',
      glutenFree: true,
      servings: 4,
      emoji: '🥗',
      gradient: ['#11998e', '#38ef7d'],
      ingredients: [
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Carrots', brand: '', match: 'Carrots', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Balsamic vinegar', 'Garlic'],
      instructions: [
        'Preheat the oven to 210°C. Cut the cauliflower into florets and the carrots into batons.',
        'Toss the cauliflower and carrots in olive oil, salt and pepper.',
        'Roast for 25–30 minutes, turning once, until caramelised and tender.',
        'Rinse and drain the chickpeas, then toss through the warm roasted vegetables.',
        'Finish with a drizzle of olive oil and balsamic vinegar.',
      ],
    },
  ],

  "PAK'nSAVE Silverdale": [
    {
      id: 'r1',
      dayOffset: 0,
      name: 'Teriyaki Chicken & Green Cabbage Stir-Fry Bowl',
      category: 'NV',
      servings: 4,
      emoji: '🍱',
      gradient: ['#ff9a56', '#ff6a88'],
      ingredients: [
        { generic: 'Cooked chicken breast, teriyaki', brand: 'Chop Chop', match: 'Chop Chop Teriyaki Pieces Of Cooked Chicken Breast', qty: 2 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
        { generic: 'Green cabbage', brand: '', match: 'Green Cabbage', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Soy sauce', 'Cooking oil', 'Garlic', 'Sesame oil'],
      instructions: [
        'Cook the rice cups according to the pack instructions (or microwave 90 seconds).',
        'Cut the green cabbage into small florets/strips.',
        'Heat a splash of cooking oil in a wok over high heat and stir-fry the green cabbage for 3–4 minutes until just tender-crisp.',
        'Add the cooked teriyaki chicken pieces and a splash of soy sauce, tossing until glossy and heated through, about 2 minutes.',
        'Finish with a few drops of sesame oil, season with salt and pepper, and serve over the warm rice.',
      ],
    },
    {
      id: 'r2',
      dayOffset: 1,
      name: 'Chickpea & Cauliflower Korma Bowl',
      category: 'V',
      glutenFree: true,
      servings: 4,
      emoji: '🍛',
      gradient: ['#f7971e', '#ffd200'],
      ingredients: [
        { generic: 'Korma curry simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Korma Simmer Sauce', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic', 'Onion'],
      instructions: [
        'Cut the cauliflower into bite-sized pieces. Rinse and drain the chickpeas.',
        'Cook the rice cups according to the pack instructions.',
        'Heat oil in a large pot, soften a diced onion and a crushed garlic clove for 2–3 minutes.',
        'Add the cauliflower, chickpeas and korma sauce, plus a splash of water. Cover and simmer 12–15 minutes until tender.',
        'Season to taste and serve over the warm rice.',
      ],
    },
    {
      id: 'r3',
      dayOffset: 2,
      name: 'Garlic Tomato Spaghetti with Green Cabbage',
      category: 'V',
      servings: 4,
      emoji: '🍝',
      gradient: ['#56ab2f', '#a8e063'],
      ingredients: [
        { generic: 'Dry spaghetti', brand: 'Diamond', match: 'Diamond Spaghetti Pasta', qty: 1 },
        { generic: 'Roasted garlic tomato & onion pasta sauce', brand: "Leggo's", match: "Leggo's Roasted Garlic Chunky Tomato & Onion Pasta Sauce", qty: 1 },
        { generic: 'Green cabbage', brand: '', match: 'Green Cabbage', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic', 'Dried basil'],
      instructions: [
        'Cook the spaghetti in a large pot of salted boiling water according to the pack instructions, then drain.',
        'Thinly slice the green cabbage.',
        'Heat a little olive oil in a large pan and soften the green cabbage for 3–4 minutes with a crushed garlic clove.',
        'Stir in the tomato & onion pasta sauce and simmer for 3–4 minutes.',
        'Toss the drained spaghetti through the sauce, season with salt, pepper and a pinch of dried basil, and serve.',
      ],
    },
    {
      id: 'r4',
      dayOffset: 3,
      name: 'Tuna & Carrots Pasta Bake',
      category: 'NV',
      servings: 4,
      emoji: '🐟',
      gradient: ['#2193b0', '#6dd5ed'],
      ingredients: [
        { generic: 'Dry penne pasta', brand: 'Diamond', match: 'Diamond Penne Pasta', qty: 1 },
        { generic: 'Tuna chunks in spring water', brand: 'Sealord', match: 'Sealord Chunky Style Tuna In Spring Water', qty: 2 },
        { generic: 'Creamy tomato & mozzarella pasta bake sauce', brand: "Leggo's", match: "Leggo's Creamy Tomato Mozzarella Pasta Bake", qty: 1 },
        { generic: 'Carrots', brand: '', match: 'Carrots', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Garlic'],
      instructions: [
        'Preheat the oven to 200°C. Cook the penne in a large pot of salted boiling water until just al dente, then drain.',
        'Dice the carrots and flake the drained tuna.',
        'Mix the cooked penne, carrots, tuna and creamy tomato bake sauce together in a baking dish, seasoning with salt, pepper and a crushed garlic clove.',
        'Bake for 15–18 minutes until bubbling, then rest 5 minutes before serving.',
      ],
    },
    {
      id: 'r5',
      dayOffset: 4,
      name: 'Vegan Black Bean & Kidney Bean Chilli',
      category: 'VG',
      servings: 4,
      emoji: '🌶️',
      gradient: ['#c31432', '#240b36'],
      ingredients: [
        { generic: 'Baked beans in tomato sauce, canned', brand: 'Oak', match: 'Oak Baked Beans In Tomato Sauce', qty: 1 },
        { generic: 'Black beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Black Beans', qty: 1 },
        { generic: 'Red kidney beans, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Red Kidney Beans', qty: 1 },
        { generic: 'Long grain rice, dry', brand: 'Fortune', match: 'Fortune Long Grain Rice', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Cumin', 'Chilli powder', 'Cooking oil', 'Onion'],
      instructions: [
        'Cook the rice according to the pack instructions.',
        'Dice the onion. Rinse and drain the black beans and kidney beans.',
        'Heat oil in a pot and soften the onion for 3–4 minutes with a pinch of cumin and chilli powder.',
        'Stir in the baked beans, black beans and kidney beans, then simmer uncovered for 12–15 minutes, stirring occasionally, until thickened.',
        'Season to taste and serve spooned over the rice.',
      ],
    },
    {
      id: 'r6',
      dayOffset: 5,
      name: 'Butter Chicken Thigh Cutlets with Rice',
      category: 'NV',
      glutenFree: true,
      servings: 4,
      emoji: '🍗',
      gradient: ['#ee0979', '#ff6a00'],
      ingredients: [
        { generic: 'Chicken thigh cutlets, bone-in', brand: '', match: 'NZ Chicken Thigh Bone in Cutlets', qty: 1 },
        { generic: 'Butter chicken simmer sauce', brand: 'Sharwoods', match: 'Sharwoods Butter Chicken Simmer Sauce', qty: 1 },
        { generic: 'Basmati rice cup, microwave', brand: 'SunRice', match: 'SunRice Basmati Rice Cups', qty: 2 },
      ],
      pantry: ['Salt', 'Pepper', 'Cooking oil', 'Garlic'],
      instructions: [
        'Season the chicken thigh cutlets with salt and pepper.',
        'Heat oil in a large pan over medium-high heat and brown the cutlets for 3–4 minutes each side.',
        'Add the butter chicken sauce and a crushed garlic clove, cover and simmer for 20–25 minutes until the chicken is cooked through, turning once.',
        'Cook the rice cups according to the pack instructions.',
        'Serve the chicken and sauce spooned over the warm rice.',
      ],
    },
    {
      id: 'r7',
      dayOffset: 6,
      name: 'Roast Cauliflower & Chickpea Salad',
      category: 'VG',
      glutenFree: true,
      servings: 4,
      emoji: '🥗',
      gradient: ['#11998e', '#38ef7d'],
      ingredients: [
        { generic: 'Cauliflower', brand: '', match: 'Cauliflower', qty: 1 },
        { generic: 'Carrots', brand: '', match: 'Carrots', qty: 1 },
        { generic: 'Chickpeas, canned', brand: 'Chantal Organics', match: 'Chantal Organics Organic Chickpeas', qty: 1 },
      ],
      pantry: ['Salt', 'Pepper', 'Olive oil', 'Balsamic vinegar', 'Garlic'],
      instructions: [
        'Preheat the oven to 210°C. Cut the cauliflower into florets and the carrots into batons.',
        'Toss the cauliflower and carrots in olive oil, salt and pepper.',
        'Roast for 25–30 minutes, turning once, until caramelised and tender.',
        'Rinse and drain the chickpeas, then toss through the warm roasted vegetables.',
        'Finish with a drizzle of olive oil and balsamic vinegar.',
      ],
    },
  ],

};
