// Converts the deal CSVs in /datadump into a single embedded JS data file
// (data.js) so the app can run by simply opening index.html — no server,
// no fetch-over-file:// CORS issues. Re-run this whenever new CSV dumps
// are dropped into /datadump.
const fs = require('fs');
const path = require('path');

const datadumpDir = path.join(__dirname, '..', 'datadump');
const outFile = path.join(__dirname, '..', 'data.js');

function parseCsvLine(line) {
  // Simple CSV split that respects double-quoted fields (none of our fields
  // currently need quoting, but this keeps it safe if they ever do).
  const cells = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; }
        else inQuotes = false;
      } else cur += c;
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ',') { cells.push(cur); cur = ''; }
      else cur += c;
    }
  }
  cells.push(cur);
  return cells.map(s => s.trim());
}

function parsePrice(str) {
  if (!str) return null;
  const m = str.match(/[\d.]+/);
  return m ? parseFloat(m[0]) : null;
}

// "4 for $5.00 ($1.25 ea)" -> { multiBuy: "4 for $5.00", each: 1.25 }
// "$0.89" -> { each: 0.89 }
function parseSalePrice(str) {
  if (!str) return { each: null, label: str || '' };
  const eaMatch = str.match(/\(\$([\d.]+)\s*ea\)/i);
  if (eaMatch) {
    return { each: parseFloat(eaMatch[1]), label: str.trim() };
  }
  const simple = str.match(/\$([\d.]+)/);
  return { each: simple ? parseFloat(simple[1]) : null, label: str.trim() };
}

function parseSaving(str) {
  if (!str) return 0;
  const m = str.match(/\$([\d.]+)/);
  return m ? parseFloat(m[1]) : 0;
}

function loadCsv(file) {
  const raw = fs.readFileSync(file, 'utf8').replace(/\r/g, '');
  const lines = raw.split('\n').filter(l => l.trim().length > 0);
  const header = parseCsvLine(lines[0]);
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    const cells = parseCsvLine(lines[i]);
    if (cells.length < 6) continue;
    const [storename, product, size, unitPrice, salePriceRaw, savingRaw] = cells;
    const sale = parseSalePrice(salePriceRaw);
    rows.push({
      store: storename,
      product,
      size: size || '',
      unitPrice: unitPrice || '',
      salePrice: sale.each,
      salePriceLabel: sale.label,
      saving: parseSaving(savingRaw),
      savingLabel: (savingRaw || '').trim(),
      onSpecial: parseSaving(savingRaw) > 0 || /for \$/.test(salePriceRaw || ''),
    });
  }
  return rows;
}

const files = fs.readdirSync(datadumpDir).filter(f => f.toLowerCase().endsWith('.csv'));
let allRows = [];
const sources = [];
for (const f of files) {
  const rows = loadCsv(path.join(datadumpDir, f));
  sources.push({ file: f, count: rows.length });
  allRows = allRows.concat(rows);
}

const dateMatch = files[0] && files[0].match(/(\d{8})/);
const dumpDate = dateMatch ? dateMatch[1] : '';

const out = `// AUTO-GENERATED by tools/build-data.js from /datadump CSVs. Do not edit by hand.
// Regenerate with: node tools/build-data.js
window.DEALS_DATA = ${JSON.stringify({ generatedFrom: sources, dumpDate, rows: allRows }, null, 0)};
`;
fs.writeFileSync(outFile, out, 'utf8');
console.log(`Wrote ${allRows.length} rows from ${files.length} file(s) to ${outFile}`);
